# Development configuration

# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  debug: true
  cors_origins:
    - "http://localhost:5173"  # Vite default port

# Database Settings
database:
  url: "sqlite:///./newslens.db"  # Using SQLite for development
  echo: true  # Log SQL queries

# Scraper Settings
scraper:
  wayback:
    base_url: "https://web.archive.org"
    cdx_api: "https://web.archive.org/cdx/search/cdx"
    user_agent: "NewsLens/1.0 (https://github.com/yogonwa/newslens)"
  live:
    user_agent: "NewsLens/1.0 (https://github.com/yogonwa/newslens)"
    timeout: 30  # seconds
    retry_attempts: 3

# Storage Settings
storage:
  screenshots_dir: "../screenshots"
  metadata_dir: "../data/metadata"
  raw_html_dir: "../data/raw_html"

# Logging Settings
logging:
  level: "DEBUG"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  file: "logs/newslens.log"

# Sources Configuration
sources:
  - name: "CNN"
    url: "https://www.cnn.com"
    extractor: "CNNHeadlineExtractor"
  - name: "Fox News"
    url: "https://www.foxnews.com"
    extractor: "FoxNewsHeadlineExtractor"
  - name: "New York Times"
    url: "https://www.nytimes.com"
    extractor: "NYTHeadlineExtractor"
  - name: "Washington Post"
    url: "https://www.washingtonpost.com"
    extractor: "WaPoHeadlineExtractor"
  - name: "USA Today"
    url: "https://www.usatoday.com"
    extractor: "USATodayHeadlineExtractor" 